"""001_Initial_Setup_Consolidated

Revision ID: 00e049d77eb1
Revises: 
Create Date: 2026-03-20 13:56:31.002716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00e049d77eb1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estudante_dados_cadastrais',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome_registro', sa.String(length=200), nullable=False),
    sa.Column('nome_social', sa.String(length=200), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('matricula_suap', sa.String(length=30), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('campus', sa.String(length=10), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('matricula_suap')
    )
    op.create_table('regra_alerta_configuracao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('queda_rendimento', 'faltas_consecutivas', 'mudanca_comportamental', 'pei_sem_revisao', name='tipoalerta'), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('condicao_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cor_visual', sa.String(length=10), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regra_motor_hipoteses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('condicoes_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hipotese_gerada', sa.Text(), nullable=False),
    sa.Column('confianca_base', sa.Integer(), nullable=False),
    sa.Column('prioridade', sa.Integer(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_perfil_acesso',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.Enum('napne', 'docente', 'gestao', 'admin', name='perfilusuario'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('dossie_perfil_longitudinal_estudante',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_estudante', sa.UUID(), nullable=False),
    sa.Column('estilo_aprendizagem', sa.String(length=100), nullable=True),
    sa.Column('perfil_cognitivo', sa.Text(), nullable=True),
    sa.Column('perfil_comportamental', sa.Text(), nullable=True),
    sa.Column('observacoes_gerais', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_estudante'], ['estudante_dados_cadastrais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_estudante')
    )
    op.create_table('matricula_entrada_sistema',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_estudante', sa.UUID(), nullable=False),
    sa.Column('curso', sa.String(length=300), nullable=False),
    sa.Column('modalidade', sa.Enum('medio_integrado', 'subsequente', 'superior', name='modalidadeensino'), nullable=False),
    sa.Column('tipo_cota_pcd', sa.Enum('nenhuma', 'pcd', 'ppi_pcd', name='tipocotapcd'), nullable=False),
    sa.Column('periodo_referencia', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('aguardando_triagem', 'entrevista_agendada', 'dossie_ativo', 'pendente_laudo', 'pendente_revisao', 'monitoramento', 'concluido', 'evadido', 'transferido', 'trancado', name='statusmatricula'), nullable=False),
    sa.Column('declarou_necessidade', sa.Boolean(), nullable=False),
    sa.Column('triagem_concluida', sa.Boolean(), nullable=False),
    sa.Column('data_matricula', sa.Date(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_estudante'], ['estudante_dados_cadastrais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerta_monitoramento_risco_estudante',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_matricula', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('queda_rendimento', 'faltas_consecutivas', 'mudanca_comportamental', 'pei_sem_revisao', name='tipoalerta'), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('dados_contexto', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('ativo', 'em_acompanhamento', 'resolvido', name='statusalerta'), nullable=False),
    sa.Column('id_responsavel', sa.UUID(), nullable=True),
    sa.Column('observacao_resolucao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolvido_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_matricula'], ['matricula_entrada_sistema.id'], ),
    sa.ForeignKeyConstraint(['id_responsavel'], ['usuario_perfil_acesso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consentimento_lgpd_estudante',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_matricula', sa.UUID(), nullable=False),
    sa.Column('versao_termo', sa.String(length=20), nullable=False),
    sa.Column('consentido', sa.Boolean(), nullable=False),
    sa.Column('ip_origem', sa.String(length=45), nullable=True),
    sa.Column('hash_documento', sa.String(length=64), nullable=True),
    sa.Column('data_consentimento', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_matricula'], ['matricula_entrada_sistema.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entrevista_estruturada_sessao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_dossie', sa.UUID(), nullable=False),
    sa.Column('id_entrevistador', sa.UUID(), nullable=False),
    sa.Column('concluida', sa.Boolean(), nullable=False),
    sa.Column('observacoes_finais', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_dossie'], ['dossie_perfil_longitudinal_estudante.id'], ),
    sa.ForeignKeyConstraint(['id_entrevistador'], ['usuario_perfil_acesso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formulario_mensal_docente_resposta',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_matricula', sa.UUID(), nullable=False),
    sa.Column('id_docente', sa.UUID(), nullable=False),
    sa.Column('mes_referencia', sa.Date(), nullable=False),
    sa.Column('nota_atual', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('frequencia_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('engajamento', sa.SmallInteger(), nullable=True),
    sa.Column('comportamento_alterado', sa.Boolean(), nullable=False),
    sa.Column('descricao_comportamento', sa.Text(), nullable=True),
    sa.Column('token_acesso', sa.UUID(), nullable=True),
    sa.Column('token_expira_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preenchido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_docente'], ['usuario_perfil_acesso.id'], ),
    sa.ForeignKeyConstraint(['id_matricula'], ['matricula_entrada_sistema.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_acesso')
    )
    op.create_table('entrevista_resposta_por_categoria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_entrevista', sa.UUID(), nullable=False),
    sa.Column('categoria', sa.Enum('desenvolvimento', 'escolarizacao', 'comportamento', 'saude', name='categoriaentrevista'), nullable=False),
    sa.Column('pergunta_codigo', sa.String(length=50), nullable=False),
    sa.Column('resposta', sa.Text(), nullable=False),
    sa.Column('indicador_risco', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_entrevista'], ['entrevista_estruturada_sessao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hipotese_diagnostica_gerada',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_entrevista', sa.UUID(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('confianca', sa.SmallInteger(), nullable=False),
    sa.Column('confirmada', sa.Boolean(), nullable=True),
    sa.Column('id_confirmado_por', sa.UUID(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_confirmado_por'], ['usuario_perfil_acesso.id'], ),
    sa.ForeignKeyConstraint(['id_entrevista'], ['entrevista_estruturada_sessao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pei_plano_educacional_individual',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_dossie', sa.UUID(), nullable=False),
    sa.Column('id_entrevista', sa.UUID(), nullable=False),
    sa.Column('id_gerado_por', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('rascunho', 'ativo', 'revisao_pendente', 'arquivado', name='statuspei'), nullable=False),
    sa.Column('gerado_automatico', sa.Boolean(), nullable=False),
    sa.Column('hash_assinatura', sa.Text(), nullable=True),
    sa.Column('data_geracao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_ultima_revisao', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_dossie'], ['dossie_perfil_longitudinal_estudante.id'], ),
    sa.ForeignKeyConstraint(['id_entrevista'], ['entrevista_estruturada_sessao.id'], ),
    sa.ForeignKeyConstraint(['id_gerado_por'], ['usuario_perfil_acesso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pei_adaptacao_curricular',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_pei', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('tempo_extra', 'avaliacao_alternativa', 'assento_preferencial', 'material_adaptado', 'interprete_libras', 'outro', name='tipoadaptacao'), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_pei'], ['pei_plano_educacional_individual.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pei_estrategia_area_curso',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_pei', sa.UUID(), nullable=False),
    sa.Column('area', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('tipo_estrategia', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_pei'], ['pei_plano_educacional_individual.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pei_objetivo_pedagogico',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_pei', sa.UUID(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('prazo', sa.String(length=50), nullable=True),
    sa.Column('alcancado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_pei'], ['pei_plano_educacional_individual.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pei_tecnologia_assistiva',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_pei', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('link_recurso', sa.Text(), nullable=True),
    sa.Column('gratuita', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_pei'], ['pei_plano_educacional_individual.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pei_tecnologia_assistiva')
    op.drop_table('pei_objetivo_pedagogico')
    op.drop_table('pei_estrategia_area_curso')
    op.drop_table('pei_adaptacao_curricular')
    op.drop_table('pei_plano_educacional_individual')
    op.drop_table('hipotese_diagnostica_gerada')
    op.drop_table('entrevista_resposta_por_categoria')
    op.drop_table('formulario_mensal_docente_resposta')
    op.drop_table('entrevista_estruturada_sessao')
    op.drop_table('consentimento_lgpd_estudante')
    op.drop_table('alerta_monitoramento_risco_estudante')
    op.drop_table('matricula_entrada_sistema')
    op.drop_table('dossie_perfil_longitudinal_estudante')
    op.drop_table('usuario_perfil_acesso')
    op.drop_table('regra_motor_hipoteses')
    op.drop_table('regra_alerta_configuracao')
    op.drop_table('estudante_dados_cadastrais')
    # ### end Alembic commands ###
