"""004_PEI_Plano_Componentes

Revision ID: 06eccca8026c
Revises: 7b8a72d465a8
Create Date: 2026-03-20 03:34:48.652570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06eccca8026c'
down_revision: Union[str, Sequence[str], None] = '7b8a72d465a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pei_plano_educacional_individual',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_dossie', sa.UUID(), nullable=False),
    sa.Column('id_entrevista', sa.UUID(), nullable=False),
    sa.Column('id_gerado_por', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('rascunho', 'ativo', 'revisao_pendente', 'arquivado', name='statuspei'), nullable=False),
    sa.Column('gerado_automatico', sa.Boolean(), nullable=False),
    sa.Column('hash_assinatura', sa.Text(), nullable=True),
    sa.Column('data_geracao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_ultima_revisao', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_dossie'], ['dossie_perfil_longitudinal_estudante.id'], ),
    sa.ForeignKeyConstraint(['id_entrevista'], ['entrevista_estruturada_sessao.id'], ),
    sa.ForeignKeyConstraint(['id_gerado_por'], ['usuario_perfil_acesso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pei_adaptacao_curricular',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_pei', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('tempo_extra', 'avaliacao_alternativa', 'assento_preferencial', 'material_adaptado', 'interprete_libras', 'outro', name='tipoadaptacao'), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_pei'], ['pei_plano_educacional_individual.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pei_estrategia_area_curso',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_pei', sa.UUID(), nullable=False),
    sa.Column('area', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('tipo_estrategia', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_pei'], ['pei_plano_educacional_individual.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pei_objetivo_pedagogico',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_pei', sa.UUID(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('prazo', sa.String(length=50), nullable=True),
    sa.Column('alcancado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_pei'], ['pei_plano_educacional_individual.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pei_tecnologia_assistiva',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_pei', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('link_recurso', sa.Text(), nullable=True),
    sa.Column('gratuita', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_pei'], ['pei_plano_educacional_individual.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pei_tecnologia_assistiva')
    op.drop_table('pei_objetivo_pedagogico')
    op.drop_table('pei_estrategia_area_curso')
    op.drop_table('pei_adaptacao_curricular')
    op.drop_table('pei_plano_educacional_individual')
    # ### end Alembic commands ###
