"""005_Alertas_Formulario_Mensal_Regras

Revision ID: 1e4e7ebfb8bc
Revises: 06eccca8026c
Create Date: 2026-03-20 03:52:24.327543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e4e7ebfb8bc'
down_revision: Union[str, Sequence[str], None] = '06eccca8026c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regra_alerta_configuracao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('queda_rendimento', 'faltas_consecutivas', 'mudanca_comportamental', 'pei_sem_revisao', name='tipoalerta'), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('condicao_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cor_visual', sa.String(length=10), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerta_monitoramento_risco_estudante',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_matricula', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('queda_rendimento', 'faltas_consecutivas', 'mudanca_comportamental', 'pei_sem_revisao', name='tipoalerta'), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('dados_contexto', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('ativo', 'em_acompanhamento', 'resolvido', name='statusalerta'), nullable=False),
    sa.Column('id_responsavel', sa.UUID(), nullable=True),
    sa.Column('observacao_resolucao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolvido_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_matricula'], ['matricula_entrada_sistema.id'], ),
    sa.ForeignKeyConstraint(['id_responsavel'], ['usuario_perfil_acesso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formulario_mensal_docente_resposta',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_matricula', sa.UUID(), nullable=False),
    sa.Column('id_docente', sa.UUID(), nullable=False),
    sa.Column('mes_referencia', sa.Date(), nullable=False),
    sa.Column('nota_atual', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('frequencia_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('engajamento', sa.SmallInteger(), nullable=True),
    sa.Column('comportamento_alterado', sa.Boolean(), nullable=False),
    sa.Column('descricao_comportamento', sa.Text(), nullable=True),
    sa.Column('token_acesso', sa.UUID(), nullable=True),
    sa.Column('token_expira_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preenchido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_docente'], ['usuario_perfil_acesso.id'], ),
    sa.ForeignKeyConstraint(['id_matricula'], ['matricula_entrada_sistema.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_acesso')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('formulario_mensal_docente_resposta')
    op.drop_table('alerta_monitoramento_risco_estudante')
    op.drop_table('regra_alerta_configuracao')
    # ### end Alembic commands ###
