"""001_Initial_Setup

Revision ID: 2e209017e16e
Revises: 
Create Date: 2026-03-20 03:00:38.615482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e209017e16e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estudante_dados_cadastrais',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome_registro', sa.String(length=200), nullable=False),
    sa.Column('nome_social', sa.String(length=200), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('matricula_suap', sa.String(length=30), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('campus', sa.String(length=10), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('matricula_suap')
    )
    op.create_table('usuario_perfil_acesso',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.Enum('napne', 'docente', 'gestao', 'admin', name='perfilusuario'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('dossie_perfil_longitudinal_estudante',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_estudante', sa.UUID(), nullable=False),
    sa.Column('estilo_aprendizagem', sa.String(length=100), nullable=True),
    sa.Column('perfil_cognitivo', sa.Text(), nullable=True),
    sa.Column('perfil_comportamental', sa.Text(), nullable=True),
    sa.Column('observacoes_gerais', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_estudante'], ['estudante_dados_cadastrais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_estudante')
    )
    op.create_table('matricula_entrada_sistema',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_estudante', sa.UUID(), nullable=False),
    sa.Column('curso', sa.String(length=300), nullable=False),
    sa.Column('modalidade', sa.Enum('medio_integrado', 'subsequente', 'superior', name='modalidadeensino'), nullable=False),
    sa.Column('periodo_referencia', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('aguardando_triagem', 'entrevista_agendada', 'dossie_ativo', 'pendente_laudo', 'pendente_revisao', 'monitoramento', 'concluido', 'evadido', 'transferido', 'trancado', name='statusmatricula'), nullable=False),
    sa.Column('declarou_necessidade', sa.Boolean(), nullable=False),
    sa.Column('triagem_concluida', sa.Boolean(), nullable=False),
    sa.Column('data_matricula', sa.Date(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_estudante'], ['estudante_dados_cadastrais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matricula_entrada_sistema')
    op.drop_table('dossie_perfil_longitudinal_estudante')
    op.drop_table('usuario_perfil_acesso')
    op.drop_table('estudante_dados_cadastrais')
    # ### end Alembic commands ###
