"""003_Entrevista_Hipoteses_Regras_Motor

Revision ID: 7b8a72d465a8
Revises: bf3c037f371d
Create Date: 2026-03-20 03:12:42.443425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b8a72d465a8'
down_revision: Union[str, Sequence[str], None] = 'bf3c037f371d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regra_motor_hipoteses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('condicoes_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hipotese_gerada', sa.Text(), nullable=False),
    sa.Column('confianca_base', sa.Integer(), nullable=False),
    sa.Column('prioridade', sa.Integer(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entrevista_estruturada_sessao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_dossie', sa.UUID(), nullable=False),
    sa.Column('id_entrevistador', sa.UUID(), nullable=False),
    sa.Column('concluida', sa.Boolean(), nullable=False),
    sa.Column('observacoes_finais', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_dossie'], ['dossie_perfil_longitudinal_estudante.id'], ),
    sa.ForeignKeyConstraint(['id_entrevistador'], ['usuario_perfil_acesso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entrevista_resposta_por_categoria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_entrevista', sa.UUID(), nullable=False),
    sa.Column('categoria', sa.Enum('desenvolvimento', 'escolarizacao', 'comportamento', 'saude', name='categoriaentrevista'), nullable=False),
    sa.Column('pergunta_codigo', sa.String(length=50), nullable=False),
    sa.Column('resposta', sa.Text(), nullable=False),
    sa.Column('indicador_risco', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_entrevista'], ['entrevista_estruturada_sessao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hipotese_diagnostica_gerada',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_entrevista', sa.UUID(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('confianca', sa.SmallInteger(), nullable=False),
    sa.Column('confirmada', sa.Boolean(), nullable=True),
    sa.Column('id_confirmado_por', sa.UUID(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_confirmado_por'], ['usuario_perfil_acesso.id'], ),
    sa.ForeignKeyConstraint(['id_entrevista'], ['entrevista_estruturada_sessao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hipotese_diagnostica_gerada')
    op.drop_table('entrevista_resposta_por_categoria')
    op.drop_table('entrevista_estruturada_sessao')
    op.drop_table('regra_motor_hipoteses')
    # ### end Alembic commands ###
