"""002_Consentimento_LGPD_Estudante

Revision ID: bf3c037f371d
Revises: 2e209017e16e
Create Date: 2026-03-20 03:05:27.076532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf3c037f371d'
down_revision: Union[str, Sequence[str], None] = '2e209017e16e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consentimento_lgpd_estudante',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_matricula', sa.UUID(), nullable=False),
    sa.Column('versao_termo', sa.String(length=20), nullable=False),
    sa.Column('consentido', sa.Boolean(), nullable=False),
    sa.Column('ip_origem', sa.String(length=45), nullable=True),
    sa.Column('hash_documento', sa.String(length=64), nullable=True),
    sa.Column('data_consentimento', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_matricula'], ['matricula_entrada_sistema.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consentimento_lgpd_estudante')
    # ### end Alembic commands ###
